### ISSUE TITLE
Korriban Academy - Various issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#162]
- [x] Opening Uthar scene: Party members need to be moved off to the side. Other prospects need shuffling into a more ordered arrangement in front of Uthar. Bring Yuthura up to stand next to Uthar. Edit: Not really practical with all the static cameras, but the party members can be jumped back out of the way.
- [x] In the introductory conversation, Uthar bows to the students, which makes no sense.
- [x] Any time Uthar is in conversation, all the wandering NPCs stop. This prevents them walking into shot, but if they are already there then they remain for the duration of the convo. They probably need to be jumped back to their starting points when the convo begins.
- [x] For Yuthura's triggered convo after Uthar, the party needs jumping.
- [x] During Dustil's convo, there's the repeated camera angle wiggle on repeated lines (presumably speaker/listener tag issues)
- [x] During Dustil's convo, Carth faces the player despite talking to Dustil
- [x] During Dustil's convo, on one node he is meant to be shaking his head, which they attempt to simulate (extremely poorly) by chaining together Look Left and Look Right animations. Either it needs a proper stunt animation, or to be removed altogether.
- [x] Uthar's datapad for Adrenas doesn't get removed from the inventory after giving it to him. Edit: Seems like the problem might be the way they rolled taking the datapad and exiting into one script, coupled with pathing issues caused by nearby NPCs. Probably needs a GIT edit to move him off to a clear spot a few meters away, and splitting the script into two and putting the datapad part on an earlier node. Edit 2: Or move the other two in front of him.
- [x] When you have enough prestige, the player bows but Uthar salutes. Would be better to have him do nothing than salute. It's weird.
- [x] When you have enough prestige and Uthar sends you to your quarters to rest, the party members may run off in the opposite direction, and/or constantly bump into the player causing pathing issues. Edit: Given the convo is dynamically initiated, a fade to black is more expedient than trying to wrangle the party.
- [x] If you trick Shaardan into giving Uthar a fake Ajunta Pall sword, there are facing issues during the cutscene of him being killed.
- [x] If you get Shaardan killed via the fake sword, his corpse is still there next to Uthar after having rested before going to the tomb of Naga Sadow (unless you save/reload in between).
- [x] When leaving for the tomb of Naga Sadow, both Uthar and the player run to the back exit. Would be better to walk them with a fade out.
- [x] Tariga should be female (per discussion below)

Added 2019-11-09:

- [x] Dustil faces Carth on the first node when he is clearly addressing the player.
- [x] There are a bunch of player freezes visible in any dynamic wide shots while Carth and Dustil are arguing. Might be easier to use a script with fire & forget anims than adding anims to each node.
- [x] There's some camera wiggle when Dustil switches between the player and Carth on two successive lines when bringing the datapad to him.
- [x] Seems that when talking to Dustil, if he goes hostile during the initial conversation that the player does not have their facing unlocked properly. The command needs to be added to k_swg_dustil99.
- [x] Interestingly, Carth did give his bark bubble "I failed you" when Dustil died the first time, but didn't when I repeated it testing the locked player fix. The first time he stayed completely passive while I choked Dustil to death, I wonder if that had something to do with it? It seems like it should always fire, since it is Dustil's default OnDeath action. Maybe when it fired the second time Carth was still considered in combat so it failed. Possibly it needs the addition of a `CancelCombat` command.

Added 2020-09-10:

- [x] The two footlockers in Uthar's room need to be rotated 90°.
- [x] Multiple placeables at the rear entrance are facing the wrong way and need to be rotated 90/180°.

**Comment by ebmar** [comment]
- [ ] In the Academy there's a Sith Student named Tamlen who describe Tariga -another student there- as a female/she, while in fact Tariga is a male/he according to the appearance and gender-check on the creature template/UTC.

The issue has been resolved by [this mod](https://deadlystream.com/files/file/1481-k1-tariga-gender-on-tamlen-dlg-fix/) with adding a new entry to the TLK which will change the female reference to male reference. Also a voice-over fix in WAV format with similar basis applied. Me as the author of the mod allowing K1CP to access the mod and incorporate the fixes with them.

Here's the appropriate setup for K1CP according to their latest `changes.ini` -

- TLK setup:
```
ID=24
SOUND=nm35aasith12029_
STRING=You simply need to follow the east passage... there's an exit there which will lead you up to the surface. Look for Tariga... he is in that area and can probably help you.
```

- DLG setup:
```
[kor35_sithfreed1.dlg]
!Destination=modules\korr_m35aa.mod
EntryList\8\Text(strref)=StrRef24
```

- Fixed voice-over to complement the string change:
[Fixed_NM35AASITH12029_.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3375963/Fixed_NM35AASITH12029_.zip)

Note that there is no LIP file with the edited voice-over, so the end-result is not perfect; particularly at the part where the change takes place. At given chance I'm looking to update the mod either with reposition the wave to exact same point as the vanilla or having the new voice-over its own specific LIP to replace the former. Either K1CP wants to include the mod and/or improving the application with their own method is greatly appreciated.

**Comment by DarthParametric** [comment]
Does Tariga have any speaking lines? If not, it would be easier to just switch the appearance to female.

**Comment by ebmar** [comment]
> Does Tariga have any speaking lines?

Yes he does. He speaks Twi'lek basic.

> ...it would be easier to just switch the appearance to female.

Yes, it could be easy enough [now] to change the `Sound` reference from male to female ones if it's decided to give them the female appearance. And I believe there's no specific characterization about Tariga is actually a male though.

**Comment by DarthParametric** [comment]
It is it just generic bark bubbles? Or an actual conversation? But I guess either way it's irrelevant if it is just generic alien speak. It can be switched either way.

**Comment by ebmar** [comment]
> It is it just generic bark bubbles? Or an actual conversation?

It's an actual conversation, though not very important - the information that comes from it could be helpful to aid insights about creatures that populate the Valley.

**Comment by DarthParametric** [comment]
Ah, I have vague memories of someone there having a piss-poor excuse for not being properly voiced. Is it down near the back door, next to the guy you give the datapad to for Uthar to poison Yuthura's bathwater?

**Comment by ebmar** [comment]
> ...next to the guy you give the datapad to for Uthar to poison Yuthura's bathwater?

Yeah, Tariga is the male student next to Adrenas.

>...someone there having a piss-poor excuse for not being properly voiced.

Yeah, perhaps it comes late at the development, or the VO files gets broken along the way, hahah.

**Comment by DarthParametric** [comment]
I'd say as a standalone mod it would make more sense to change the character to make them an actual Twi'lek. But that's probably too radical for the Community Patch, since it would require rewriting the conversation. 

I suppose we should poll @JCarter426 and @Mako88 on whether we switch the character to female to match the existing reference, or switch the other person's dialogue to match the existing appearance (using ebmar's mod).

**Comment by Mako88** [comment]
So it's a male human that speakes Twi'lek and is referred to as a she? I vote we change the appearance to Twi'lek and make her a girl.

**Comment by JCarter426** [comment]
I believe his and/or her dialogue specifies that they're not Twi'lek, unless that was the other Twi'lek-speaking human I'm thinking of.

Either way, I'd also go with female.

**Comment by DarthParametric** [comment]
Yeah the convo I am remembering goes out of its way to address the non-Twi'lek thing, which was why I said above that it would require changing the entire DLG. I also prefer the female route, so I guess no dice for you @ebmar

**Comment by JCarter426** [comment]
I'll probably incorporate it into my next Korriban update. I have to figure out what to do about compatibility with ebmar's male alternative in both cases, so I'll procrastinate until we're closer to release.

**Comment by ebmar** [comment]
> ...I guess no dice for you...

Cool. And yeah, by changing the appearance to female human also makes Tariga the only one with Twi'lek Basic - which makes her unique, certainly.

> I believe his and/or her dialogue specifies that they're not Twi'lek...

Yes, though there's no references about Tariga specifically a Human from any of the NPC, but this response from the PC should be suffice as a confirmation -
- > You're human, but you speak like a Twi'lek...

**Comment by DarthParametric** [comment]
Seems that when talking to Dustil, if he goes hostile during the initial conversation that the player does not have their facing unlocked properly. The command needs to be added to k_swg_dustil99.

**Comment by Salk73** [comment]
DP,

I was testing the first cutscene when entering the Sith Academy and I noticed you decided to jump only two party members rather than all of them. Is there a specific reason for it?

**Comment by DarthParametric** [comment]
Both the footlockers in Uthar's room need rotating 90°.

Reported by @Salk73.

**Comment by Salk73** [comment]
This should fix the problem with the orientation of several backpacks, lockers and one footlocker in the training hall:

```
[m35aa.git]
!Destination=modules\korr_m35aa.mod
Placeable List\22\Bearing=-1.570795
Placeable List\28\Bearing=3.14159
Placeable List\29\Bearing=-1.570795
Placeable List\30\Bearing=-2.3566135
Placeable List\31\Bearing=3.14159
Placeable List\32\Bearing=1.570795
Placeable List\34\Bearing=-1.570795
Placeable List\39\Bearing=1.570795
Placeable List\40\Bearing=1.570795
Placeable List\41\Bearing=3.14159
Placeable List\97\Bearing=1.570795
```
I have noticed that the backpack model used there doesn't seem to have any volume. It is possible to walk through it like if it was an hologram. Since I know nothing about modelling I submit to you whether or not this is something that should be addressed by the K1 CP.

**Comment by DarthParametric** [comment]
No model actually has any "volume" as such. What you are talking about is a walkmesh for static objects (characters use "personal space" dynamic collision, defined in appearance.2da). It would be easy enough to create a PWK for the backpack, although it's possible that could introduce unintended issues by screwing up pathfinding somewhere.

**Comment by JCarter426** [comment]
I believe the reason the backpack has no walkmesh is that it's also one of the placeables used for creature remains.

**Comment by DarthParametric** [comment]
_Technically_ it does have a PWK, but it contains no geometry, so there is no collision. But yeah that probably explains it. I guess we won't be touching it then.

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] One of the footlockers in Uthar's room is still not correctly aligned.

![Uthar_Footocker](https://user-images.githubusercontent.com/46890653/144402649-001ee0ad-7536-46a9-8556-07dda5023bf1.jpg)

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] It seems that Lashowe is not being correctly jumped to her quarters after the opening Uthar scene ends. She's stuck in front of one of the doors in the central chamber. I suspect the original must have used `ActionJumpToObject` with the `nWalkStraightLineToPoint` option set to TRUE and that this was changed in the rework of the scene.

**Comment by DarthParametric** [comment]
Found the problem with Lashowe. It is due to #423. Obviously it was too close and she couldn't reach it due to the computer terminal's collision.

**Comment by DarthParametric** [comment]
1.10.0 beta test 2 observations:

- [ ] If you gave Shaardan a fake sword, the party needs to be jumped for the start of the scene with him being killed by Uthar.
- [ ] At the start of the fake sword scene, Shaardan is also doing the pray/meditate anim in front of Uthar, which seems odd. Would make more sense to have him walk up to Uthar from off-screen.
